/*
    FUNÇÕES DE DATA E HORA
*/

-- GETDATE
SELECT GETDATE() AS [DATA E HORA ATUAL];


-- DATEADD
SELECT 
    GETDATE() AS [DATA E HORA ATUAL],
    DATEADD(DAY, 10, GETDATE()) AS [DATA DAQUI 10 DIAS],
    DATEADD(DAY, -48, GETDATE()) AS [DATA 48 DIAS ATRAS];


-- DATEDIFF
SELECT
    GETDATE() AS [DATA E HORA ATUAL],
    DATEDIFF(DAY, '2025-01-01', GETDATE()) AS [DIAS DESDE INICIO DO ANO],
    DATEDIFF(HOUR, '2025-01-01', GETDATE()) AS [HORAS DESDE INICIO DO ANO],
    DATEDIFF(MONTH, '2025-01-01', GETDATE()) AS [MESES DESDE INICIO DO ANO];


--DATEPART
SELECT
    GETDATE() AS [DATA E HORA ATUAL],
    DATEPART(DAY, GETDATE()) AS DIA,
    DATEPART(MONTH, GETDATE()) AS MES,
    DATEPART(YEAR, GETDATE()) AS ANO,
    DATEPART(HOUR, GETDATE()) AS HORA,
    DATEPART(MINUTE, GETDATE()) AS MINUTO;


--DATENAME
SELECT
    DATENAME(DAY,GETDATE()) + ' ' +
    DATENAME(MONTH, GETDATE()) + ' ' +
    DATENAME(YEAR, GETDATE())