/*
    FUNÇÕES  PARA NÚMEROS
*/

-- ROUND, CEILING, FLOOR
SELECT
    ROUND(3.437, 2) AS [ROUND ACIMA],
    ROUND(3.433,2) AS [ROUND ABAIXO],
    CEILING(3.433) AS [CEILING],
    FLOOR(3.433) AS [FLOOR];


-- POWER, EXP,  SQRT, ABS
SELECT 
    POWER(2, 3) AS [POWER(2,3)],
    EXP(1) AS [EXP(1)],
    EXP(2) AS [EXP(2)],
    SQRT(144) AS [SQRT(144)],
    ABS(-15) AS [ABS(-15)];

