/*
    LOCALIZAR CLIENTES QUE ESTÃO EM BAIRROS
    ONDE EXISTEM VENDEDORES
*/

-- TOTAL DE CLIENTES E VENDEDORES
SELECT COUNT(*) FROM Clientes
SELECT COUNT(*) FROM Vendedores;

--
SELECT DISTINCT
    V.Nome AS VENDEDOR,
    V.Bairro AS [BAIRRO VENDEDOR],
    C.Nome AS CLIENTE,
    C.Bairro AS [BAIRRO CLIENTE]
FROM Clientes C
INNER JOIN Vendedores V
ON C.Bairro = V.Bairro;


-- VENDEDOR SEM CLIENTE NO BAIRRO
SELECT DISTINCT
    V.Nome AS VENDEDOR,
    V.Bairro AS [BAIRRO VENDEDOR],
    C.Nome AS CLIENTE,
    C.Bairro AS [BAIRRO CLIENTE]
FROM Clientes C
RIGHT JOIN Vendedores V
ON C.Bairro = V.Bairro;


-- CLIENTE SEM VENDEDOR NO BAIRRO
SELECT DISTINCT
    V.Nome AS VENDEDOR,
    V.Bairro AS [BAIRRO VENDEDOR],
    C.Nome AS CLIENTE,
    C.Bairro AS [BAIRRO CLIENTE]
FROM Clientes C
LEFT JOIN Vendedores V
ON C.Bairro = V.Bairro;